name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  sonarcloud:
    name: Test and Code Quality Report (SonarCloud)
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v5
        with:
          args: >
            -Dsonar.projectVersion=${{ github.run_id }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_CLOUD_TOKEN }}
          LC_ALL: "C.UTF-8"
