name: Update Demos
on:
  repository_dispatch:
    types: update_embed_demos

jobs:
  update-demos:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - run: echo "Update demos"
